version: '2.4'
services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8003:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  loadGenerator:
    image: loadgen-0.0.1
    container_name: loadGenerator
    ports:
      - 8001:8080
    cpuset: "0"
    cpus: '4'
    mem_limit: 1024M
